FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

RUN apt-get update && apt-get install -y wget git gcc g++ cmake libfst-dev ninja-build

RUN mkdir -p ~/miniconda3 && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-py311_24.4.0-0-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
    rm -rf ~/miniconda3/minicond

ENV PATH="/root/miniconda3/bin:${PATH}"
RUN pip install transformers -U
RUN pip install torch
RUN pip install accelerate
RUN pip install vllm
